import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "../static/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between w-[100%]">
          <div className="w-[15%]">
            <Sidebar />
          </div>
          <div className="w-[85%]"> {children}</div>
        </div>
      </body>
    </html>
  );
}
